//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaOrderManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PizzaOrders_tb
    {
        public int OrderId { get; set; }
        public string NameOfCustomer { get; set; }
        public string FlavourOfPizza { get; set; }
        public string SizeOfThePizza { get; set; }
        public decimal BilledAmount { get; set; }
        public string Address { get; set; }
        public string DeliveryStatus { get; set; }
        public string TypeOfPayment { get; set; }
        public System.DateTime CreateDate { get; set; } = DateTime.Now;
    }
}
